CREATE TABLE estoque._vicostumers (
    COSTUMER_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL, 
	CPF CHAR(11) NOT NULL, 
	COSTUMER_REGISTRY NUMBER(10,0) NOT NULL, 
	COSTUMER_STORE NUMBER(3,0) NOT NULL, 
	FIRST_NAME VARCHAR2(25) NOT NULL, 
	LAST_NAME VARCHAR2(25) NOT NULL, 
	ADMISSION_DATE DATE, 
	ACTIVE_STATUS CHAR(1) NOT NULL, 
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL, 
	UPDATED_AT DATE NOT NULL, 
	PRIMARY KEY (COSTUMER_ID));